// <auto-generated />
using System;
using FooBar.Infrastructure.DataSource;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FooBar.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240809004826_AddData")]
    partial class AddData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FooBar.Domain.Entities.Voter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Voter");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66c7678d-7741-40ad-bc37-597abbcfcaa6"),
                            DateOfBirth = new DateTime(2024, 8, 8, 19, 48, 26, 164, DateTimeKind.Local).AddTicks(1175),
                            Nid = "1033796537",
                            Origin = "Colombia"
                        },
                        new
                        {
                            Id = new Guid("b0cbb9b3-8342-487b-bd99-2d71fb9d150b"),
                            DateOfBirth = new DateTime(2024, 8, 8, 19, 48, 26, 164, DateTimeKind.Local).AddTicks(1306),
                            Nid = "1033796537",
                            Origin = "Peru"
                        },
                        new
                        {
                            Id = new Guid("fe037753-d3e1-4f4a-a2ed-470c3841aa15"),
                            DateOfBirth = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nid = "51765132",
                            Origin = "COLOMBIA"
                        },
                        new
                        {
                            Id = new Guid("f2cc58c7-fdad-4957-b507-27fc585a05ca"),
                            DateOfBirth = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nid = "79254420",
                            Origin = "COLOMBIA"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
